name: Telegram Kino Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Bot 24/7
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        CHANNEL_URL: ${{ secrets.CHANNEL_URL }}
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
      run: node index.js
